DROP TABLE IF EXISTS services;
CREATE TABLE IF NOT EXISTS services (
    ServiceId INTEGER PRIMARY KEY,
    service_name TEXT,
    description TEXT,
    category TEXT,
    subcategory TEXT,
    tags TEXT,
    features TEXT
);

INSERT INTO services (ServiceId, service_name, description, category, subcategory, tags, features) VALUES
(1, 'Asphalt Paving Installation', 'Professional asphalt paving installation services ensuring durable and smooth surfaces for driveways, roads, and parking lots, enhancing both functionality and appearance.', 'Asphalt Paving', 'Installation', 'Driveways\nRoads\nParking Lots\nPathways\nIdeal For Residential\nCommercial\nIndustrial Properties', 'Our Services Are Tailored To Meet The Specific Needs Of Each Client. Our Asphalt Paving Installation service includes site preparation, base installation, asphalt laying, and finishing. We start with a thorough assessment of the site conditions, followed by meticulous preparation and professional application techniques. Our goal is to deliver a finished product that exceeds your expectations in both appearance and durability.'),
(2, 'Asphalt Paving Resurfacing', 'Quality asphalt resurfacing services to restore and extend the life of your asphalt surfaces, providing a cost-effective solution to maintain your property's aesthetic and structural integrity.', 'Asphalt Paving', 'Resurfacing', 'Driveways\nRoads\nParking Lots\nPathways\nResidential Properties\nCommercial Properties\nIndustrial Properties', 'Our Asphalt Paving Resurfacing service includes surface cleaning, minor repairs, new asphalt layer application, and finishing. We start with a thorough assessment of the site conditions, followed by meticulous preparation and professional application techniques. Our goal is to deliver a finished product that exceeds your expectations in both appearance and durability.'),
(3, 'Asphalt Paving Replacement', 'Comprehensive asphalt paving replacement services to renew your worn-out surfaces with high-quality materials, ensuring a fresh, durable, and visually appealing result.', 'Asphalt Paving', 'Replacement', 'Driveways\nRoads\nParking Lots\nPathways\nResidential Properties\nCommercial Properties\nIndustrial Properties\nNew Driveway\nParking Lot Resurfacing\nRoutine Maintenance', 'Our Asphalt Paving Replacement service includes old asphalt removal, base preparation, new asphalt installation, and finishing. We start with a thorough assessment of the site conditions, followed by meticulous preparation and professional application techniques. Our goal is to deliver a finished product that exceeds your expectations in both appearance and durability.'),
(4, 'Asphalt Paving Extension', 'Efficient asphalt paving extension services to expand existing paved areas, offering more space and functionality while maintaining a seamless integration with current surfaces.', 'Asphalt Paving', 'Extension', 'Driveways\nRoads\nParking lots\nPathways\nResidential properties\nCommercial properties\nIndustrial properties\nNew driveway\nParking lot resurfacing\nRoutine maintenance', 'Our Asphalt Paving Extension service includes surface preparation, base installation, asphalt laying, and finishing. We start with a thorough assessment of the site conditions, followed by meticulous preparation and professional application techniques. Our goal is to deliver a finished product that exceeds your expectations in both appearance and durability.'),
(5, 'Sealcoating', 'High-quality seal coating services to protect and enhance your asphalt surfaces, extending their lifespan and maintaining their appearance against weather damage and wear.', 'Sealer', 'Sealcoating', 'Surface cleaning\nSealant application\nDrying time\nSurface inspection\nRegular maintenance\nFinal inspection\nResidential properties\nCommercial properties\nIndustrial properties\nNew driveway\nParking lot resurfacing\nRoutine maintenance', 'Our Seal Coating service includes surface cleaning, sealant application, and finishing. We start with a thorough assessment of the site conditions, followed by meticulous preparation and professional application techniques. Our goal is to deliver a finished product that exceeds your expectations in both appearance and durability.'),
(6, 'Asphalt Maintenance', 'Comprehensive asphalt maintenance services including repairs and regular upkeep to prolong the life and performance of your asphalt surfaces.', 'Sealer', 'Asphalt Maintenance', 'Regular inspections\nCrack sealing\nPothole repair\nSeal coating\nSurface cleaning\nFinal inspection\nResidential properties\nCommercial properties\nIndustrial properties\nNew driveway\nParking lot resurfacing\nRoutine maintenance', 'Our Asphalt Maintenance service includes inspection, crack sealing, pothole repair, and seal coating. We start with a thorough assessment of the site conditions, followed by meticulous preparation and professional application techniques. Our goal is to deliver a finished product that exceeds your expectations in both appearance and durability.'),
(7, 'Crack Filling', 'Effective crack filling services to prevent water infiltration and further damage, maintaining the integrity and longevity of your asphalt surfaces.', 'Sealer', 'Crack Filling', 'Crack cleaning\nFiller application\nSurface leveling\nDrying time\nFinal inspection\nResidential applications\nCommercial applications\nIndustrial applications\nDriveways\nRetaining walls', 'Our Crack Filling service includes crack cleaning, filler application, and finishing. Our process begins with a comprehensive site assessment to understand your specific needs, followed by detailed preparation and expert execution. We aim to provide a final product that not only meets but surpasses your expectations in both appearance and durability.'),
(8, 'Line Striping', 'Professional line striping services to ensure clear, durable markings for parking lots, roads, and other asphalt surfaces, enhancing safety and organization.', 'Sealer', 'Line Striping', 'Surface cleaning\nLine layout\nPaint selection\nPaint application\nDrying time\nFinal inspection\nResidential applications\nCommercial applications\nIndustrial applications\nDriveways\nRetaining walls', 'Our Line Striping service includes surface preparation, paint selection, and application. Our process begins with a comprehensive site assessment to understand your specific needs, followed by detailed preparation and expert execution. We aim to provide a final product that not only meets but surpasses your expectations in both appearance and durability.'),
(9, 'Pavers Installation', 'Expert paver installation services to create beautiful, durable, and functional outdoor spaces, from driveways to patios and walkways.', 'Pavers', 'Pavers Installation', 'Design consultation\nMaterial sourcing\nSurface preparation\nPaver placement\nJoint filling\nFinal inspection\nResidential applications\nCommercial applications\nIndustrial applications\nDriveways\nRetaining walls', 'Our Pavers Installation service includes design consultation, material selection, installation, and finishing. Our process begins with a comprehensive site assessment to understand your specific needs, followed by detailed preparation and expert execution. We aim to provide a final product that not only meets but surpasses your expectations in both appearance and durability.'),
(10, 'Paver Maintenance', 'Comprehensive paver maintenance services to keep your outdoor spaces looking their best and functioning properly.', 'Pavers', 'Pavers Maintenance', 'Regular inspections\nPower washing\nSealant application\nCrack repair\nJoint replacement\nFinal inspection\nResidential applications\nCommercial applications\nIndustrial applications\nDriveways\nRetaining walls', 'Our Pavers Maintenance service includes inspection, cleaning, sealing, and repairs. Our process begins with a comprehensive site assessment to understand your specific needs, followed by detailed preparation and expert execution. We aim to provide a final product that not only meets but surpasses your expectations in both appearance and durability.'),
(11, 'Retaining Walls', 'Professional retaining wall construction services to provide structural support and enhance the landscape of your property.', 'Pavers', 'Retaining Walls', 'Gardens\nSloped areas\nProperty borders\nErosion control\nResidential applications\nCommercial applications\nIndustrial applications\nDriveways\nRetaining walls', 'Our Retaining Wall service includes site assessment, design, material selection, construction, and finishing. Our process begins with a comprehensive site assessment to understand your specific needs, followed by detailed preparation and expert execution. We aim to provide a final product that not only meets but surpasses your expectations in both appearance and durability.'),
(12, 'Belgium blocks', 'Quality Belgium block installation services to add a touch of elegance and durability to your landscaping projects.', 'Pavers', 'Belgium blocks', 'Design planning\nMaterial sourcing\nSurface preparation\nBlock placement\nJoint filling\nFinal inspection\nResidential applications\nCommercial applications\nIndustrial applications\nDriveways\nRetaining walls', 'Our Belgium Blocks service includes design consultation, material selection, installation, and finishing. Our process begins with a comprehensive site assessment to understand your specific needs, followed by detailed preparation and expert execution. We aim to provide a final product that not only meets but surpasses your expectations in both appearance and durability.'),
(13, 'Walkways', 'Expert walkway installation services to create safe, attractive, and durable paths in your outdoor spaces.', 'Concrete', 'Walkways', 'Site evaluation\nDesign planning\nMaterial sourcing\nConstruction\nSurface finishing\nFinal inspection\nResidential applications\nCommercial applications\nIndustrial applications\nWalkways\nTopsoil application', 'Our Walkways service includes design consultation, material selection, construction, and finishing. Our process begins with a comprehensive site evaluation to understand your specific needs, followed by meticulous preparation and professional installation. We aim to provide a final product that not only meets but surpasses your expectations in both appearance and durability.'),
(14, 'Sidewalks', 'High-quality sidewalk installation services to ensure safe and durable pedestrian pathways, enhancing the accessibility and appearance of your property.', 'Concrete', 'Sidewalks', 'Site evaluation\nExcavation\nMaterial sourcing\nInstallation\nRepairs\nFinal inspection\nResidential applications\nCommercial applications\nIndustrial applications\nWalkways\nTopsoil application', 'Our Sidewalks service includes site preparation, material selection, installation, and repairs. Our process begins with a comprehensive site evaluation to understand your specific needs, followed by meticulous preparation and professional installation. We aim to provide a final product that not only meets but surpasses your expectations in both appearance and durability.'),
(15, 'Curbs', 'Professional curb installation services to create a defined edge for roads and parking lots, improving the overall appearance and functionality.', 'Concrete', 'Curbs', 'Road edges\nParking lots\nWalkways\nDriveways\nResidential applications\nCommercial applications\nIndustrial applications\nTopsoil application', 'Our Curb Installation service includes site preparation, precise curb setting, material selection, and finishing. Our process begins with a comprehensive site evaluation to understand your specific needs, followed by meticulous preparation and professional installation. We aim to provide a final product that not only meets but surpasses your expectations in both appearance and durability.'),
(16, 'Aprons', 'Durable apron installation services to provide a smooth transition between your driveway and the road, ensuring easy access and a neat appearance.', 'Concrete', 'Aprons', 'Driveway transitions\nWalkway entries\nGarage entrances\nRoad connections\nResidential applications\nCommercial applications\nIndustrial applications\nTopsoil application\nWalkways', 'Our Apron Installation service includes site preparation, material selection, precise laying, and finishing. Our process begins with a comprehensive site evaluation to understand your specific needs, followed by meticulous preparation and professional installation. We aim to provide a final product that not only meets but surpasses your expectations in both appearance and durability.'),
(17, 'Sod Installation', 'High-quality sod installation services to create lush, green lawns quickly and efficiently, enhancing the beauty of your outdoor spaces.', 'Landscaping', 'Sod Installation', 'Lawns\nGardens\nRecreational areas\nCommercial landscapes\nResidential applications\nCommercial applications\nIndustrial applications\nTopsoil application\nWalkways', 'Our Sod Installation service includes soil preparation, sod selection, installation, and initial watering and care instructions. Our process begins with a comprehensive site evaluation to understand your specific needs, followed by meticulous preparation and professional installation. We aim to provide a final product that not only meets but surpasses your expectations in both appearance and durability.'),
(18, 'Top Soil', 'High-quality topsoil delivery and spreading services to enrich your garden and landscaping projects.', 'Landscaping', 'Top Soil', 'Gardens\nLawns\nFlower beds\nLandscaping projects\nResidential applications\nCommercial applications\nIndustrial applications\nTopsoil application\nWalkways', 'Our Top Soil service includes soil delivery, site preparation, spreading, and leveling. Our process begins with a comprehensive site evaluation to understand your specific needs, followed by meticulous preparation and professional installation. We aim to provide a final product that not only meets but surpasses your expectations in both appearance and durability.'),
(19, 'Seed Grass', 'Expert grass seeding services to establish a healthy, green lawn from scratch, ensuring proper growth and coverage.', 'Landscaping', 'Seed Grass', 'Lawns\nGardens\nParks\nSports fields\nResidential applications\nCommercial applications\nIndustrial applications\nGrass seeding\nWinter services', 'Our Seed Grass service includes soil preparation, seed selection, sowing, and initial watering and care instructions. Our process begins with a thorough site evaluation to understand your specific needs, followed by meticulous preparation and professional execution. We aim to provide a final product that not only meets but surpasses your expectations in both appearance and durability.'),
(20, 'Gutters', 'Professional drainage solutions to manage water runoff and prevent water damage, maintaining the health and stability of your property.', 'Landscaping', 'Gutters', 'Residential roofs\nCommercial roofs\nBuilding perimeters\nDrainage systems\nResidential applications\nCommercial applications\nIndustrial applications\nGrass seeding\nWinter services', 'Our Gutter service includes gutter installation, regular cleaning, repairs, and inspection. Our process begins with a thorough site evaluation to understand your specific needs, followed by meticulous preparation and professional execution. We aim to provide a final product that not only meets but surpasses your expectations in both appearance and durability.'),
(21, 'Drainage', 'Professional gutter installation and maintenance services to protect your property from water damage and improve drainage.', 'Landscaping', 'Drainage', 'Site evaluation\nDrainage system design\nInstallation\nRegular maintenance\nFlood prevention\nFinal inspection\nResidential applications\nCommercial applications\nIndustrial applications\nGrass seeding\nWinter services', 'Our Drainage service includes site assessment, system design, installation, and maintenance. Our process begins with a thorough site evaluation to understand your specific needs, followed by meticulous preparation and professional execution. We aim to provide a final product that not only meets but surpasses your expectations in both appearance and durability.'),
(22, 'Power Wash', 'High-quality power washing services to clean and restore the appearance of your exterior surfaces, removing dirt, grime, and stains.', 'Landscaping', 'Power Wash', 'Surface assessment\nHigh-pressure washing\nMold and mildew removal\nStain treatment\nFinal inspection\nResidential applications\nCommercial applications\nIndustrial applications\nGrass seeding\nWinter services', 'Our Power Washing service includes surface assessment, high-pressure cleaning, and post-cleaning inspection. Our process begins with a thorough site evaluation to understand your specific needs, followed by meticulous preparation and professional execution. We aim to provide a final product that not only meets but surpasses your expectations in both appearance and durability.'),
(23, 'Hauling', 'Efficient hauling services to remove debris and unwanted materials from your property, ensuring a clean and tidy environment.', 'Landscaping', 'Hauling', 'Debris removal\nYard waste disposal\nRecycling services\nClean-up\nFlexible scheduling\nFinal inspection\nResidential applications\nCommercial applications\nIndustrial applications\nGrass seeding\nWinter services', 'Our Hauling service includes debris removal, yard waste disposal, recycling, and clean-up. Our process begins with a thorough site evaluation to understand your specific needs, followed by meticulous preparation and professional execution. We aim to provide a final product that not only meets but surpasses your expectations in both appearance and durability.'),
(24, 'Winter Services', 'Reliable winter services including snow removal and ice management to keep your property safe and accessible during the winter months.', 'Landscaping', 'Winter Services', 'Snow plowing\nSalting\nDe-icing\nEmergency snow removal\nIce management\nFinal inspection\nResidential applications\nCommercial applications\nIndustrial applications', 'Our Winter Services include snow plowing, salting, de-icing, and emergency snow removal. Our process begins with a thorough site evaluation to understand your specific needs, followed by meticulous preparation and professional execution. We aim to provide a final product that not only meets but surpasses your expectations in both appearance and durability.');
